### ISSUE TITLE
Hi! nice job! And can you share me with UR-funny dataset (better contain raw videos), thanks

### ISSUE THREAD

**Issue by yan9qu** [yliu-cs/CVLA#1]

**Comment by yliu-cs** [comment]
Thank you for your kind words! I am pleased that you found the paper appreciable.
The UR-FUNNY dataset, inclusive of raw videos, was obtained from the official repository [ROC-HCI/UR-FUNNY](https://github.com/ROC-HCI/UR-FUNNY).
Have a great day!

**Comment by yan9qu** [comment]
> Thank you for your kind words! I am pleased that you found the paper appreciable. The UR-FUNNY dataset, inclusive of raw videos, was obtained from the official repository [ROC-HCI/UR-FUNNY](https://github.com/ROC-HCI/UR-FUNNY). Have a great day!

Thank you for your prompt reply! I sent you an email with further inquiries, thank you
